---
- name: Prepare GUID environment variable across all hosts
  hosts: all
  tasks:
    - name: All GUID env variable
      shell: export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc

- name: Script setup
  hosts: localhost
  tasks: 
    - name: "Script setup permision set.."
      shell: chmod 755 ./scripts/script_setup.sh
    - name: "Setting up the scripts.."
      shell: ./scripts/script_setup.sh

- name: Verify Installation and Configuration of Docker
  hosts: nodes
  tasks:
    - name: docker restart
      shell: systemctl restart docker
      
- name: Generate Inventory Hosts File
  hosts: localhost
  tasks:
    - name: Generate Inventory script
      script: /root/ocp_advanced_deployment_homework/scripts/generate_inventory.sh

- name: Execute the openshift-ansible prerequisites
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

- name: Execute the openshift-ansible Deployer
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

- name: Verify OpenShift Cluster
  hosts: masters[0]
  tasks:
    - name: copy the .kube directory from master1 to your bastion
      fetch: 
        src: "/root/.kube/config"
        dest: "/root/.kube/config"
        flat: "yes"

- name: Post installation configuration
  hosts: localhost
  tasks:
    - name: make sure you are system:dmin
      shell: oc whoami | grep system:admin

- name: Create PVs
  hosts: nfs
  tasks:
    - name: Create PVs
      script: ./scripts/create_pvs.sh
    - name: Restarting NFS Server...
      shell: systemctl restart nfs-server

- name: Create 25 files for 5G and 10G PVs
  hosts: localhost
  tasks:
    - name: Create 25 files for 5G PVs
      script: ./scripts/pvs_5Gsize.sh
    - name: Create 25 files for 10G PVs
      script: ./scripts/pvs_10Gsize.sh

- name: Create all PVs for OCP
  hosts: localhost
  tasks:
    - name: Create all PVs for OCP
      shell: cat /root/pvs/* | oc create -f -
      
- name: Fix NFS Persistent Volume Recycling
  hosts: nodes
  tasks:
    - name: Pull ose-recycler image
      shell: docker pull registry.access.redhat.com/openshift3/ose-recycler:latest
    - name: Tag  ose-recycler image as latest
      shell: docker tag registry.access.redhat.com/openshift3/ose-recycler:latest registry.access.redhat.com/openshift3/ose-recycler:v3.9.30

- name: Setup CI/CD pipeline
  hosts: localhost
  tasks:
    - name: Checkout CI/CD demo code..
      git:
        repo: 'https://github.com/berrutig/openshift-cd-demo-1.git'
        dest: /root/openshift-cd-demo
        version: ocp-3.9
    - name: Permissions..
      shell: sed -i -e 's/\r$//' /root/openshift-cd-demo/scripts/provision.sh
    - name: Adding permissions
      shell: chmod 755 /root/openshift-cd-demo/scripts/provision.sh
    - name: Permissions..
      shell: sed -i -e 's/\r$//' /root/openshift-cd-demo/cicd-template.yaml
    - name: Adding rest of permissions
      shell: chmod 755 /root/openshift-cd-demo/cicd-template.yaml   
    - name: Provision the demo environment..
      shell: /root/openshift-cd-demo/scripts/provision.sh --user andrew deploy
      
- name: Setup project request template
  hosts: localhost 
  tasks: 
    - name: Create project request template in default project
      shell: "oc create -f ./project-template.yaml -n default || oc replace -f ./project-template.yaml -n default"

- name: Update the master config file to use project request template
  hosts: masters
  tasks:
    - name: Add the project request template to the master config"
      lineinfile:
        regexp: "  projectRequestTemplate"
        dest: "/etc/origin/master/master-config.yaml"
        line: '  projectRequestTemplate: "default/project-request"'
        state: present
    - name: Restart master API service 
      service:
        name: atomic-openshift-master-api
        state: restarted

- name: Smoke Test
  hosts: localhost
  tasks:
    - name: Create the smoke-test project
      shell: oc new-project smoke-test
    - name: Deploy the test app
      shell: oc new-app --namespace smoke-test nodejs-mongo-persistent 
    
- name: Creation of projects for Alpha and Beta clients
  hosts: localhost
  tasks:
    - name: Create alpha project
      shell: oc new-project alpha
    - name: Create beta project
      shell: oc new-project beta

- name: Creation of users for Alpha and Beta clients
  hosts: masters
  tasks:
    - name: Adding users for alpha and beta
      shell: for user in amy andrew brian betty; do htpasswd -b /etc/origin/master/htpasswd $user r3dh4t1!; done

- name: Kick off the pipeline
  hosts: localhost
  tasks:
    - name: Wait for the demo environment to fully spin up
      shell: sleep 300 
    - name: Kick off the pipeline
      shell: oc start-build tasks-pipeline -n tasks-dev

- name: HPA configuration on production
  hosts: localhost
  tasks:
    - name: Wait for tasks pipeline to build
      shell: sleep 800 
    - name: Configure autoscaling on openshift-tasks..
      shell: oc autoscale dc tasks --max 5 --min 2 --cpu-percent 80 -n tasks-prod

- name: Multitenancy Test
  hosts: localhost
  tasks:
    - name: Multitenancy Test
      script: ./scripts/multitenancy.sh
